function _typeof(f){"@babel/helpers - typeof";_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(d){return typeof d}:function(d){return d&&"function"===typeof Symbol&&d.constructor===Symbol&&d!==Symbol.prototype?"symbol":typeof d};return _typeof(f)}
function _inherits(f,d){if("function"!==typeof d&&null!==d)throw new TypeError("Super expression must either be null or a function");f.prototype=Object.create(d&&d.prototype,{constructor:{value:f,writable:!0,configurable:!0}});d&&_setPrototypeOf(f,d)}function _setPrototypeOf(f,d){_setPrototypeOf=Object.setPrototypeOf||function(k,m){k.__proto__=m;return k};return _setPrototypeOf(f,d)}
function _createSuper(f){var d=_isNativeReflectConstruct();return function(){var k=_getPrototypeOf(f);if(d){var m=_getPrototypeOf(this).constructor;k=Reflect.construct(k,arguments,m)}else k=k.apply(this,arguments);return _possibleConstructorReturn(this,k)}}function _possibleConstructorReturn(f,d){if(d&&("object"===_typeof(d)||"function"===typeof d))return d;if(void 0!==d)throw new TypeError("Derived constructors may only return object or undefined");return _assertThisInitialized(f)}
function _assertThisInitialized(f){if(void 0===f)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return f}function _isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(f){return!1}}
function _getPrototypeOf(f){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(d){return d.__proto__||Object.getPrototypeOf(d)};return _getPrototypeOf(f)}
function _createForOfIteratorHelper(f,d){var k="undefined"!==typeof Symbol&&f[Symbol.iterator]||f["@@iterator"];if(!k){if(Array.isArray(f)||(k=_unsupportedIterableToArray(f))||d&&f&&"number"===typeof f.length){k&&(f=k);var m=0;d=function(){};return{s:d,n:function(){return m>=f.length?{done:!0}:{done:!1,value:f[m++]}},e:function(z){throw z;},f:d}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}var F=!0,G=!1,I;return{s:function(){k=k.call(f)},n:function(){var z=k.next();F=z.done;return z},e:function(z){G=!0;I=z},f:function(){try{if(!F&&null!=k["return"])k["return"]()}finally{if(G)throw I;}}}}
function _unsupportedIterableToArray(f,d){if(f){if("string"===typeof f)return _arrayLikeToArray(f,d);var k=Object.prototype.toString.call(f).slice(8,-1);"Object"===k&&f.constructor&&(k=f.constructor.name);if("Map"===k||"Set"===k)return Array.from(f);if("Arguments"===k||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(k))return _arrayLikeToArray(f,d)}}function _arrayLikeToArray(f,d){if(null==d||d>f.length)d=f.length;for(var k=0,m=Array(d);k<d;k++)m[k]=f[k];return m}
function _classCallCheck(f,d){if(!(f instanceof d))throw new TypeError("Cannot call a class as a function");}function _defineProperties(f,d){for(var k=0;k<d.length;k++){var m=d[k];m.enumerable=m.enumerable||!1;m.configurable=!0;"value"in m&&(m.writable=!0);Object.defineProperty(f,m.key,m)}}function _createClass(f,d,k){d&&_defineProperties(f.prototype,d);k&&_defineProperties(f,k);return f}
!function(){function f(b,a){var c=[];if(!b)return c;for(var e=b.length;e--;)c[e]=b[e];return c.slice(a)}function d(b,a){if(b)for(var c=0;c<b.length;c++){var e=a.call(this,b[c],c);if(void 0!==e)return e}}function k(b,a){if(b instanceof Array)d(b,function(g,l){a(g,l,l)});else{var c=0,e;for(e in b)Object.hasOwnProperty.call(b,e)&&a(b[e],e,c++)}}function m(b,a){var c;b.parentNode||(null===(c=a.parentNode)||void 0===c?void 0:c.insertBefore(b,a))}function F(b){var a;null===(a=b.parentNode)||void 0===a?
void 0:a.removeChild(b)}function G(b){function a(){delete b["#animateCancel"];b.classList.remove(g);null===q||void 0===q?void 0:q();clearTimeout(A)}function c(){null===l||void 0===l?void 0:l();a()}var e,g=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"fadeIn",l=2<arguments.length?arguments[2]:void 0;null===(e=b["#animateCancel"])||void 0===e?void 0:e.call(b);b.classList.add(g);if(e=T(b,"animationDuration",parseFloat))var q=U(b,"animationend",c),A=setTimeout(c,1E3*e);else c();return b["#animateCancel"]=
a}function I(b,a,c){if(b["#animateRemoved"]||!b.parentNode)b["#animateRemoved"]=!1,m(b,a),G(b,c,function(){})}function z(b,a){b["#animateRemoved"]||(b["#animateRemoved"]=!0,G(b,a,function(){F(b)}))}function P(b,a){var c,e="".concat(a);if(b[e])return b[e];a=" ".concat(a,": ").concat(b.cloneNode().outerHTML," ").concat(null!==(c=b["@key"])&&void 0!==c?c:"");c=document.createComment(a);b.parentNode.insertBefore(c,b);b[e]=c;c["#node"]=b;return c}function J(b,a){var c;return(null===b||void 0===b?void 0:
null===(c=b.getAttribute)||void 0===c?void 0:c.call(b,a))||""}function C(b,a){var c;null===b||void 0===b?void 0:null===(c=b.removeAttribute)||void 0===c?void 0:c.call(b,a)}function T(b,a){return(2<arguments.length&&void 0!==arguments[2]?arguments[2]:String)(getComputedStyle(b)[a])}function U(b,a,c){b.addEventListener(a,c);return function(){b.removeEventListener(a,c)}}function K(b,a){var c=K["prop:".concat(a)];if(c)return c;for(c in b)if(c.toLowerCase()===a)return K["prop:".concat(a)]=c;return a={class:"className"}[a]||
a}function Q(b){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:'"';return"".concat(a).concat(b.replace(/\\/g,"\\\\").replace(/['"]/g,"\\$&").replace(/\r?\n/g,"\\n")).concat(a)}function R(b){var a=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"}";return b.replace(RegExp("(\\".concat(1<arguments.length&&void 0!==arguments[1]?arguments[1]:"{",")((\"(\\.|[^])*?\"|'(\\.|[^])*?'|`(\\.|[^])*?`|{[^]*?}|[^])*?)(\\").concat(a,")"),"g"),"\f +($2)+ \f").replace(/(^|\f)([^]*?)(\f|$)/g,function(c,
e,g,l){return Q(g)})}function V(b){if(b=/([^(,)\s]+)()()(?:\s+in\s+)([^(,)\s]+)/.exec(b)||/\(\s*([^(,)\s]+)\s*,\s*([^(,)\s]+)()\s*\)(?:\s+in\s+)([^(,)\s]+)/.exec(b)||/\(\s*([^(,)\s]+)\s*,\s*([^(,)\s]+)\s*,\s*([^(,)\s]+)\s*\)(?:\s+in\s+)([^(,)\s]+)/.exec(b)||/(?:var|let|const)(?:\s+)()([^(,)\s]+)()(?:\s+in\s+)([^(,)\s]+)/.exec(b)||/(?:var|let|const)(?:\s+)([^(,)\s]+)()()(?:\s+of\s+)([^(,)\s]+)/.exec(b))return{list:b[4],item:b[1]||"$item",key:b[2]||"$key",index:b[3]||"$index"}}function W(b,a){b=b.replace(/\/\/.*|\/\*[^]*?\*\//g,
"");for(var c=[],e=/(var|let|const)(\s+)(.*?)(\s|=|,|;|$)/g,g;g=e.exec(b);)g=g[3],c.push(g),null===a||void 0===a?void 0:a(g);return c}function X(b){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"props",c="\n";b.forEach(function(e){c+='!!("'.concat(e,'" in ').concat(a,") && (").concat(e,"=").concat(a,".").concat(e,")\n")});return c}function Y(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"self.render()";return"\n  var setTimeout = function(cb, delay, a,b,c,d,e){\n    return window.setTimeout(function(){\n      cb(a,b,c,d,e)\n      ".concat(b,
"\n    }, delay) \n  }\n  var setInterval = function(cb, delay, a,b,c,d,e){\n    return window.setInterval(function(){\n      cb(a,b,c,d,e)\n      ").concat(b,"\n    }, delay) \n  }\n  ")}function B(b,a){try{Function(b)}catch(e){try{Function("(".concat(b,")"))}catch(g){var c=a.parentNode||a;a=a.nodeValue||a.cloneNode().outerHTML;a=a.replace(/<\/.*?>/,"");a=c.outerHTML.replace(a,"\ud83d\udc1e"+a+"\ud83d\udc1e");b=b.replace(/;"#(.*?)#";/g,"$1");throw Error("[TemplateError] ".concat(e,"\n").concat(b,
"\n^\n").concat(a,"\n"));}}}var Z=function(){function b(a){_classCallCheck(this,b);this.nodeMap={length:0};this.forPath="";this.target=this.el=null;this["#tpl"]=a;this.compile(a)}_createClass(b,[{key:"saveNode",value:function(a){var c=a.nodeValue||a.cloneNode().outerHTML;2===a.nodeType&&(c="[".concat(a.nodeName,"=").concat(a.nodeValue,"]"));c=a["@id"]||"".concat(this.nodeMap.length++,": ").concat(c," ").replace(/\s+/g," ").replace(/'/g,'"').replace(/\\/g,"");this.nodeMap[c]=a;return a["@id"]=c}},
{key:"getNode",value:function(a){var c;if(null!==(c=a)&&void 0!==c&&c.nodeType)return a;a="".concat(a).concat(this.forPath);c=this.nodeMap[a];if(!c)throw a;return c}},{key:"for",value:function(a,c,e){var g=this,l=this.getNode(a),q=P(l,"#for#");F(l);var A=l["@cloneNodes"]=l["@cloneNodes"]||{},D=this.forPath;k(c,function(u,w,L){g.forPath="".concat(D,"#").concat(w);var h=A[w];h||(h=l.cloneNode(!0),h["#for#"]=q,h["@key"]=w,A[w]=h,function x(v,r){v["@originNode"]=r["@originNode"]||r;v["@id"]="".concat(v["@originNode"]["@id"]).concat(g.forPath);
g.saveNode(v);d(v.childNodes,function(M,H){return x(M,r.childNodes[H])})}(h,l));g["if"](h,!0);e.call(g,u,w,L)});this.forPath=D;k(A,function(u,w){if(!Object.hasOwnProperty.call(c,w))g["if"](u,!1)})}},{key:"if",value:function(a,c,e){var g;a=this.getNode(a);a=(null===(g=a["@component"])||void 0===g?void 0:g.el)||a;g=a["#if#"]||a["#for#"];if(c){var l,q=(null===(l=a["@originNode"])||void 0===l?void 0:l["@in"])||a["@in"];I(a,g,q);e&&e.call(this)}else P(a,"#if#"),e=(null===(q=a["@originNode"])||void 0===
q?void 0:q["@out"])||a["@out"],z(a,e)}},{key:"prop",value:function(a,c,e){a=this.getNode(a);a.$props=a.$props||{};a.$props[c]!==e&&(a.$props[c]=e,a[c]=e)}},{key:"on",value:function(a,c,e){}},{key:"is",value:function(a,c){function e(l,q){q.prototype instanceof b&&(l["@component"]?l["@component"].render(l.$props):(new q).mount(l))}var g=this.getNode(a);null!==c&&void 0!==c&&c.then?c.then(function(l){return e(g,l)}):e(g,c)}},{key:"compile",value:function(a){function c(h){var p=e.saveNode(h);g+="// ".concat(p,
"\n");if(!/^(skip|script|style|template)$/i.test(h.tagName))if(3===h.nodeType&&/\{[^]*?\}/.test(h.nodeValue)){var v=R(h.nodeValue);g+="self.prop('".concat(p,"', 'nodeValue', ").concat(v,")\n");B(v,h)}else{v=J(h,"for");var r=V(v);r&&(g+="self['for']('".concat(p,"', ").concat(r.list,", function(").concat(r.item,",").concat(r.key,",").concat(r.index,"){\n"),B(v.replace(/var|let|const/g,';"#$&#";').replace(/of/,';"#$&#";'),h),C(h,"for"));if(r=J(h,"if"))g+="self['if']('".concat(p,"', ").concat(r,", function(){\n"),
B(r,h),C(h,"if");d(f(h.attributes),function(y){var t=y.nodeName,n=y.nodeValue;/^class$/i.test(t)&&/:/.test(n)&&(n=n.replace(/([^'"\s]+):([^'"\s]+)/g,'{$2?"$1":""}'));if(/^class$/i.test(t)){var E,N;h["@in"]=null===(E=/([^'"\s]+)@in/.exec(n))||void 0===E?void 0:E[1];h["@out"]=null===(N=/([^'"\s]+)@out/.exec(n))||void 0===N?void 0:N[1]}/^style$/i.test(t)&&/([_\[])(.+?)([_\]])/.test(n)&&(n=n.replace(/([_\[])(.+?)([_\]])/g,"{$2}"));/^[\.:]value/.test(t);/^[\.:]/.test(t)?(E=K(h,t.substr(1)),g+="self.prop('".concat(p,
"', '").concat(E,"', ").concat(n,")\n"),B(n,y),C(h,t)):/\{[^]*?\}/.test(n)?(E=K(h,t),n=R(n),g+="self.prop('".concat(p,"', '").concat(E,"', ").concat(n,")\n"),B(n,y),C(h,t)):/^(on|@)/.test(t)?(g+="self.prop('".concat(p,"', \"").concat(t.replace("@","on"),'", function(){').concat(n,"; self.render()})\n"),B(n,y),C(h,t)):/^\$$/.test(t)&&(g+=";".concat(n,"=self.getNode('").concat(p,"')\n"),B(n,y),C(h,"$"))});var x=J(h,"is");if(x)g+="self.is('".concat(p,"', ").concat(x,")\n"),B(x,h),C(h,"is");else{x=_createForOfIteratorHelper(D);
var M;try{for(x.s();!(M=x.n()).done;){var H=M.value;if(/^[A-Z]/.test(H)&&RegExp("^".concat(H,"$"),"i").test(h.tagName)){g+="self.is('".concat(p,"', ").concat(H,")\n");break}}}catch(y){x.e(y)}finally{x.f()}}d(f(h.childNodes),function(y){return c(y)});r&&(g+="})\n");v&&(g+="})\n")}}var e=this,g="\n",l="\n",q="\n",A=!1,D=[],u=a;"string"===typeof a&&(u=document.createElement("div"),u.innerHTML=a);A=u==document.documentElement;u.querySelectorAll("script").forEach(function(h){return q+=h.innerHTML});u.querySelectorAll("template").forEach(function(h){var p=
J(h,"name");p&&(l+="\n          var ".concat(p," = this.constructor.prototype.").concat(p,"\n          if(!").concat(p,"){\n            ").concat(p," = this.defineSubComponent(").concat(Q(h.innerHTML),")\n            this.constructor.prototype.").concat(p," = ").concat(p,"\n          }\n        "))});D=W("".concat(l,";").concat(q));e["#varNames"]=D;c(u);this.render=Function("component_","\n      // debugger\n      var self = this\n\n      // initCode\n      ".concat(l,"\n\n      // async function\n      ").concat(Y(),
"\n\n      // <script>\n      ").concat(A?"/* global */":q,"\n\n      function render($props){\n        // debugger\n\n        // props\n        $props = $props || {}\n        ").concat(X(D,"$props"),"\n\n        // code\n        ").concat(g,"\n      }\n\n      function get(name){\n        get[name] = get[name] || eval('(function(){return '+name+'})')\n        return get[name]()\n      }\n      function set(name, value){\n        set[name] = set[name] || eval('(function(){return '+name+'='+value+'})')\n        return set[name](value)\n      }\n      this.get = get\n      this.set = set\n\n      return render\n    ")).call(this,
this);this.el=null;a=_createForOfIteratorHelper(u.children);var w;try{for(a.s();!(w=a.n()).done;){var L=w.value;if(!/style|script/i.test(L.tagName)){this.el=L;break}}}catch(h){a.e(h)}finally{a.f()}this["#node"]=u;this.el["#component"]=this}},{key:"defineSubComponent",value:function(a){return function(c){function e(){_classCallCheck(this,e);return g.call(this,a)}_inherits(e,c);var g=_createSuper(e);return e}(b)}},{key:"mount",value:function(a){this.target=a;this.render(null===a||void 0===a?void 0:
a.$props);a&&(a["@component"]=this,a.parentNode&&a.parentNode.replaceChild(this.el,a));a=this.constructor;a["#styled"]||(this["#node"].querySelectorAll("style").forEach(function(c){document.head.appendChild(c)}),a["#styled"]=!0);b["#ci"]=b["#ci"]||1;a["#c"]=a["#c"]||b["#ci"]++;this.el.setAttribute("c".concat(a["#c"]),"");return this.el}}]);return b}();if("object"===("undefined"===typeof window?"undefined":_typeof(window))&&this===window){var O=function(){},S=window.setInterval;window.setInterval=
function(b,a){return S(function(){var c=b.apply(this,arguments);O();return c},a)};var aa=window.setTimeout,ba=window.requestAnimationFrame;window.requestAnimationFrame=function(b,a){return ba(function(){var c=b.apply(this,arguments);O();return c},a)};addEventListener("DOMContentLoaded",function(b){var a=new Z(document.documentElement);window.app=a;window.render=a.render;a.render();O=function(){a.render()};window.setTimeout=aa;window.setInterval=S})}}();